// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0D-sHbUqOp2tdSe-VxOAlHANA6Ar5DhI',
    appId: '1:222764086185:web:e076b702df76d0897a0ab8',
    messagingSenderId: '222764086185',
    projectId: 'chat-app-20ebe',
    authDomain: 'chat-app-20ebe.firebaseapp.com',
    storageBucket: 'chat-app-20ebe.appspot.com',
    measurementId: 'G-S79VK7Q162',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0fdqgt19T2_FRPzZBWz339CLDxOOYHxQ',
    appId: '1:222764086185:android:f4ce3c77338d9ab67a0ab8',
    messagingSenderId: '222764086185',
    projectId: 'chat-app-20ebe',
    storageBucket: 'chat-app-20ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqlAISB2Z-lbd17EzpBiwDcR5kigp1JI',
    appId: '1:222764086185:ios:bdefcb541d40d9667a0ab8',
    messagingSenderId: '222764086185',
    projectId: 'chat-app-20ebe',
    storageBucket: 'chat-app-20ebe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqlAISB2Z-lbd17EzpBiwDcR5kigp1JI',
    appId: '1:222764086185:ios:44752a716065219f7a0ab8',
    messagingSenderId: '222764086185',
    projectId: 'chat-app-20ebe',
    storageBucket: 'chat-app-20ebe.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
